#ifndef COMMUNICATE_GLOBAL_H
#define COMMUNICATE_GLOBAL_H

#ifdef _MSVC_

#  define COMMUNICATESHARED_EXPORT

#else

#if defined(COMMUNICATE_LIBRARY)
#  define COMMUNICATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMUNICATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif

#endif // COMMUNICATE_GLOBAL_H
